[package]
name = "isar-core"
version = "0.0.0"
authors = ["Simon Choi"]
edition = "2021"

[dependencies]
itertools = "0.11"
enum_dispatch = "0.3.8"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
serde =  { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
byteorder = "1"
intmap = "2.0.0"
snafu = "0.7.0"
ouroboros = "0.17"
base64 = "0.21.0"
paste = "1.0.12"
parking_lot = "0.12"
proc-macro2 = "1.0.66"
arc-swap = "1.6.0"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"

libsqlite3-sys = { git = "https://github.com/isar/rusqlite.git", branch = "wasm", features=["bundled"], optional = true  }
mdbx-sys = { package = "mdbx-sys", path = "../mdbx_sys", optional = true  }

[target.'cfg(target_os = "windows")'.dependencies]
widestring = "1.0"

[dev-dependencies]
rand = "0.8.5"
cfg-if = "1"
float_next_after = "1"

[dev-dependencies.serde_json]
version = "*"
features = ["float_roundtrip"]

[features]
default = ["native", "sqlite"]
native = ["mdbx-sys"]
sqlite = ["libsqlite3-sys"]
sqlcipher = ["sqlite", "libsqlite3-sys/bundled-sqlcipher"]
sqlcipher-vendored = ["sqlcipher", "libsqlite3-sys/bundled-sqlcipher-vendored-openssl"]